config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root "users#index"
  get '/user/information', to: "users#information"
  resources :users do
     resources :events do
      resources :invitations , only: [:create]
     end
     resources :categories, only: [:create]
  end
  resources :attend_events
  resources :categories,only: [ :index]

  default_url_options :host => 'localhost:3000'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attend_event.rb
class AttendEvent < ApplicationRecord
    belongs_to :attendee, class_name:"User" 
    belongs_to :attended_event, class_name:"Event"
    
    scope :get_id,-> (attendee) {where('attendee_id=? ',attendee).ids}
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  has_many :event_categories,dependent: :destroy
  has_many :events,through: :event_categories,source: :event

  validates :title, presence: true
end

app/models/event.rb
class Event < ApplicationRecord

    scope :old,-> {where('created_at <= ?', Time.now - (3600*24))}
    scope :recent,->{where('created_at > ?', Time.now-(3600*24))}

    has_many :attend_events , foreign_key: :attended_event_id , dependent: :destroy
    has_many :attendees , through: :attend_events , source: :attendee
    belongs_to :creator , class_name:"User"

    has_many :invitations , foreign_key: :event_id , class_name:"Invitation" , dependent: :destroy
    has_many :invited_users, through: :invitations, source: :invited

    has_many :event_categories,dependent: :destroy
    has_many :categories,through: :event_categories,source: :category

    validates :event_date, presence: true
    validates :location, presence: true
    
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  belongs_to :event
  belongs_to :category
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :inviter, class_name:"User"
    belongs_to :invited, class_name:"User"
    belongs_to :event, class_name:"Event"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :categories 
    
    has_many :attend_events,foreign_key: :attendee_id , dependent: :destroy
    has_many :attended_events,through: :attend_events 

    has_many :events, foreign_key: :creator_id, class_name: "Event", dependent: :destroy

    has_many :inviter_invitations, foreign_key: :inviter_id , class_name:"Invitation", dependent: :destroy
    has_many :invited_users , through: :inviter_invitations , source: :invited
    
    has_many :invited_invitation , foreign_key: :invited_id , class_name:"Invitation",dependent: :destroy
    has_many :inviters , foreign_key: :invited_invitations 

    validates :name, presence: true
    
    has_secure_password
    validates :password, presence: true , length: {minimum:6}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum:255}, format: { with: VALID_EMAIL_REGEX } , uniqueness: true
    
    VALID_PHONE_REGEX = /\A\(?(?:\d{2})?\)?[- ]?\d{3}[- ]?\d{3}\z/i
    validates :phone, presence: true , format: { with: VALID_PHONE_REGEX }

    validates :date_of_birth, presence: true
    validates :address, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/attend_events_controller.rb
class AttendEventsController < ApplicationController

    def create
        user = User.find(params[:user_id])
        event = Event.find(params[:attended_event_id])
        attend_event = AttendEvent.new 
        attend_event.attendee_id = user.id
        attend_event.attended_event_id = event.id
        
       if attend_event.save
           redirect_to user
       end
    end
    def destroy
        attend_event = AttendEvent.find(params[:id])
        attend_event.destroy
        redirect_to user_path(attend_event.attendee_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all
    end

    def create
        @user = User.find(params[:user_id])
        @category = @user.categories.build(category_params)
        if @category.save!
            flash[:success]="Category is successfuly added"
            redirect_to @user
        end
    end

    private 
    def category_params 
        params.require(:category).permit(:title)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        events = Event.all
        @old_events = events.old
        @recent_events = events.recent
        @user = User.find(params[:user_id])
    end

    def create
        @user = User.find(params[:user_id])
        categories = params[:categories]
        if @user.events.create(event_params)
          event = Event.find_by(event_params)
          categories.each do |cat|
            category = Category.find(cat)
            EventCategory.create(event: event ,category: category )
          end
          flash[:success]= "New event was added!!"
          redirect_to user_path(@user)
       end
    end

    def edit
        @user = User.find(params[:user_id])
        @event =Event.find(params[:id])
    end

    def update
       @user = User.find(params[:user_id])
       @event = Event.find(params[:id]) 
       if @event.update(event_params)
          flash[:success] = "The event was successfully updated!!"
          redirect_to user_path(@user)
       end
    end

    def destroy
        user = User.find(params[:user_id])
        event = user.events.find_by(id: params[:id])
        event.destroy
        redirect_to user_path(user)
    end

    private 
    
    def event_params 
        params.require(:event).permit(:event_date,:location,:creator_id)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    
    def create
        invitation = Invitation.new(inviter_id: params[:user_id],invited_id: params[:invited_user],event_id: params[:event_id])
        @current_user = params[:user_id]
        if invitation.save
            redirect_to user_path(@current_user )
        else 
            flash[:danger] = "Failed to invite user !!"
            redirect_to user_path(@current_user)
        end
    end
    private 

    def invitation_params 
        params.require(:invitation).permit(:user_id,:event_id,:invited_users)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all 
    end

    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)

        if @user.save 
            flash[:success]="A new user was created !!"
            redirect_to @user
        else 
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
        @users = User.where.not(id: @user.id)
        @categories = Category.all
    end

    def edit
        @user = User.find(params[:id])
    end

    def update

        @user = User.find(params[:id])

        if @user.update(user_params)
            flash[:success] = "User Information Was Successfuly Updated. Please Check Your Email !!"
            UserMailer.user_updated_information(@user).deliver_now
            redirect_to @user
        else
           render :edit
        end

    end

    def information
        @user = User.find(params[:user])
    end

    private 
    def user_params 
        params.require(:user).permit(:name,:password,:password_confirmation,:email,:phone,:date_of_birth,:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attend_events_helper.rb
module AttendEventsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Categories List:</h1>
<ul>
<% @categories.each do |cat| %>
  <li> <h3><%= cat.title.capitalize %></h3>
    <h4>Events belong to this category:</h4>
    <ol>
    <% cat.events.each do |event| %>
    <li>
    location: <%= event.location %><br>
    Date: <%= event.event_date %><br>
    Creator Of event : <%= event.creator.name.capitalize %>  
    </li>
    <% end %>
    </ol>
<% end %>
</ul>

app/views/events/_event.html.erb
<li>
  The location of event: <%= event.location %>.<br>
  Date of event: <%= event.event_date %>.
  <%= form_with model: event.attend_events.build,data: {turbo:false} do |f| %>
      <div>
       <%= hidden_field_tag :user_id, @user.id %>
       <%= hidden_field_tag :attended_event_id, event.id %>
       
      </div>
      <% if event.attendees.include?(@user) || event.creator_id == @user.id %>
        <% if event.creator_id == @user.id %>
         <p style="color:green">Creator Of The Event</p>
         <% else %>
        <p style="color:purple">Attended</p>
        <% end %>
      <% else %>
        <%= f.submit "Attend" %>
      <% end %>
  <% end %>
</li>
<% if event.attendees.include?(@user) %>
<%= button_to "Delete Attendee", attend_event_path(event.attend_events.get_id(@user.id)) ,method: :delete, :onclick => "return confirm('Are you sure you want to delete your self from the attendee list? ')" %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit The Event For User <%= @user.name.titleize %></h1>

<%= form_with model:[@user,@event] ,data: {turbo:false} do |f| %>

  <%= f.label :location %><br>
  <%= f.text_field :location %><br><br>
  <%= f.label :event_date %><br>
  <%= f.datetime_field :event_date %><br><br>

   <%= f.submit "Edit" %>
<% end %>

app/views/events/index.html.erb
<h2><%= link_to "Back To User List" ,root_path %> |
<%= link_to "Go back",user_path(@user) %><h2>

<h1> List of Events</h1>
   
  <h2>Recent Event</h2>
  <ol>
    <% @recent_events.each do |event| %>
       <% if event.invited_users.include?(@user) || @user.id == event.creator_id %>
         <%= render event %>
       <% end %>
    <% end %>
 </ol>

  <h2>Old Events</h2>
  <ol>
    <% @old_events.each do |event| %>
      <% if event.invited_users.include?(@user) || @user.id == event.creator_id %>
         <%= render event %>
       <% end %>
    <% end %>
 </ol>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |message_type,message| %>
     <div style="color:green"><h3><%= message %></h3></div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
<div style="color:red" >
<div >
 <h2>The form contains <%= pluralize(object.errors.count,"error") %></h2>
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
<% end %>
</ul>
</div>    
<% end %>

app/views/shared/_form.html.erb
<%= form_with model:@user, data: {turbo:false} do |f| %>
  <%= render 'shared/error_message',object: f.object %>
   <%= f.label :name %><br>
   <%= f.text_field :name %><br><br>

   <%= f.label :email %><br>
   <%= f.text_field :email , placeholder:"example@gmail.com" %><br><br>
   
   <%= f.label :password %><br>
   <%= f.password_field :password %><br><br>

   <%= f.label :password_confirmation %><br>
   <%= f.password_field :password_confirmation %><br><br>
   
   <%= f.label :phone %><br>
   <%= f.text_field :phone , placeholder:"00-000-000 or without -" %><br><br>

   <%= f.label :date_of_birth %><br>
   <%= f.date_field :date_of_birth %><br><br>

   <%= f.label :address %><br>
   <%= f.text_field :address %><br>
   <br>
   <%= f.submit  %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Information</h1>

<%= render 'shared/form' %>

app/views/users/index.html.erb
<h2><%= link_to "New User", new_user_path %></h2>
<h1>Users List</h1>

<%= form_with model: @user, data: {turbo:false} do |f| %>
 <h3>
  <ol>
  <% @users.each do |user| %>
      <li>
        
        <%= user.name.titleize %>.<br>
         View the page of user: <%= link_to "Show page", user_path(user)%><br>
      </li>
      <br>
  <% end %>
  </ol>
  </h3>
<% end %>

app/views/users/information.html.erb
<h1>User Information: </h1>

<ol>
  <li>Name: <%= @user.name.titleize %></li>
  <li>Email: <%= @user.email %></li>
  <li>Phone: <%= @user.phone %></li>
  <li>Date of Birth: <%= @user.date_of_birth %></li>
  <li>Address: <%= @user.address %></li>
</ol>

app/views/users/new.html.erb
<h1>Creating New User</h1>

<%= render 'shared/form' %>

app/views/users/show.html.erb
<h2>  <%= link_to "Go to the list of events", user_events_path(@user) %> |
  <%= link_to "User list" , root_path %> | <%= link_to "Edit User Information" , edit_user_path(@user)%>|<%= link_to "Categories List" , categories_path%></h2>
<h1>Events Created by <%= @user.name.titleize %></h1>

 <% if @user.events.any? %>
   <ul> 
      <% @user.events.each do |event| %>
      <li>
       The location : <%= event.location %>.<br>
       The date : <%= event.event_date %> | 
       <%= link_to "Edit Event", edit_user_event_path(@user,event) %>
       <%= button_to "Delete event",[@user,event], method: :delete %>
       
         <h3>Invitation :</h3>
          <ol>
           <% @users.each  do |user| %>
           <% if @user.invited_users.include?(user) && event.invited_users.include?(user)%>
           <li> 
             <p><%= user.name.titleize %><p>
             <p style="color:purple"> Invited</p> 
           </li>
           <br>
           <% else %>
           <li>
             <%= form_with url:user_event_invitations_path(@user,event), data: {turbo: false} do |f| %>
               <%= user.name.titleize %>
               <%= hidden_field_tag :invited_user , user.id %><br>
               <%= f.submit "Invite User" %>
             <% end %> 
           </li>
           <br>
           <% end %>
           <% end %>
          </ol>
      </li>
      <br>
      <% end %>
   </ul>
 <% end %>

 <% if @user.attend_events.any? %>
 <h2>Attended Events</h2>
    <ol>
       <% @user.attended_events.each do |attended_event| %>
          <li> 
               The location : <%= attended_event.location %>.<br>
               The date : <%= attended_event.event_date %>

          </li>
       <% end %>
    </ol>
 <% end %>

 <h3>Add Categories</h3>
 <%= form_with model: [@user, @user.categories.build ] ,data: {turbo: false} do |f| %>
    
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>
 
    <%= f.submit "Add Category" %>
    
  <% end %>

 <p> <h3>Add Event</h3>
  <%= form_with model: [@user, @user.events.build ] ,data: {turbo: false} do |f| %>
    
    <%= f.label :event_date, "Event date" %><br>
    <%= f.datetime_field :event_date %><br><br>
    <%= f.label :location %><br>
    <%= f.text_field :location %><br>
      <h4>Categories:</h4>
      <% @categories.each do |category| %>
          <%= f.label category.title %> 
          <%= check_box_tag 'categories[]', category.id  %> <br/>
     <% end %>
     <br>
    <%= f.submit "Add event" %>
    
  <% end %>
 </p>